import {authenticate,origin} from '../../../../backend/auth';
import {body,failure,HttpError} from '../../../../backend/config';
import {transaction} from '../../../../backend/database';
import {ingest,approve,reviewed,exportAudit} from '../../../../documents/store';
import {compileExport} from '../../../../documents/export';
import {z} from 'zod';
export const runtime='nodejs';
export async function GET(request:Request){try{const p=await authenticate(request,'documents:read');const url=new URL(request.url);const id=url.searchParams.get('id');if(!id)return Response.json({documents:await transaction(p,async c=>(await c.query('SELECT id,request_id,name,mime,status,version::text,report FROM custodia.documents ORDER BY created_at DESC LIMIT 100')).rows)},{headers:{'Cache-Control':'no-store'}});z.uuid().parse(id);if(url.searchParams.get('format')==='preview'){const document=await reviewed(p,id,false);return new Response(new Uint8Array(document.bytes),{headers:{'Content-Type':document.mime==='application/pdf'?'application/pdf':'text/plain; charset=utf-8','Cache-Control':'no-store','Content-Disposition':`inline; filename="custodia-${id}"`,'Content-Security-Policy':"sandbox; default-src 'none'",'X-Content-Type-Options':'nosniff'}});}const format=z.enum(['csv','xlsx','jsonld','pdf']).parse(url.searchParams.get('format'));if(!p.scopes.has('documents:export'))throw new HttpError(403,'Export permission required');const document=await reviewed(p,id,true);const file=await compileExport(document,format);const audit=await exportAudit(p,id,format,file.hash);return new Response(new Uint8Array(file.bytes),{headers:{'Content-Type':file.mime,'Content-Disposition':`attachment; filename="custodia-${id}.${file.extension}"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Custodia-SHA256':file.hash,'X-Custodia-Signature':audit.signature,'X-Custodia-Proof':Buffer.from(audit.proof).toString('base64url'),'X-Custodia-Key-ID':audit.keyId}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{origin(request);const p=await authenticate(request,'documents:write');const id=z.uuid().parse(request.headers.get('x-request-id'));const name=z.string().min(1).max(200).parse(decodeURIComponent(request.headers.get('x-document-name')??''));const rawPolicy=request.headers.get('x-redaction-policy');if(!rawPolicy||rawPolicy.length>20000)throw new HttpError(400,'Bounded redaction policy required');const policy=JSON.parse(Buffer.from(rawPolicy,'base64url').toString('utf8'));const mime=request.headers.get('content-type')?.split(';')[0]??'';const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'Binary body required');const chunks:Uint8Array[]=[];let size=0;for(;;){const next=await reader.read();if(next.done)break;size+=next.value.length;if(size>5*1024*1024){await reader.cancel();throw new HttpError(413,'Document too large');}chunks.push(next.value);}return Response.json(await ingest(p,id,name,mime,Buffer.concat(chunks),policy),{status:201});}catch(e){return failure(e);}}
export async function PATCH(request:Request){try{origin(request);const p=await authenticate(request,'documents:approve');const input=z.object({id:z.uuid(),version:z.string().regex(/^[1-9][0-9]*$/),confirmed:z.literal(true)}).strict().parse(await body(request));return Response.json(await approve(p,input.id,input.version));}catch(e){return failure(e);}}
