import {createCipheriv,createDecipheriv,randomBytes,createHash} from 'node:crypto';
import {required,httpsUrl,HttpError} from './config';
import {createRemoteJWKSet,jwtVerify} from 'jose';
export function cookie(request:Request,name:string){return request.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1);}
function key(){const value=required('SESSION_ENCRYPTION_KEY');if(!/^[a-f0-9]{64}$/i.test(value))throw new Error('Session key must be 32 bytes hex');return Buffer.from(value,'hex');}
export function seal(value:unknown){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key(),iv);const data=Buffer.concat([cipher.update(JSON.stringify(value)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64url');}
export function open(value:string){if(value.length>12000)throw new HttpError(401,'Session rejected');try{const data=Buffer.from(value,'base64url');const cipher=createDecipheriv('aes-256-gcm',key(),data.subarray(0,12));cipher.setAuthTag(data.subarray(12,28));return JSON.parse(Buffer.concat([cipher.update(data.subarray(28)),cipher.final()]).toString());}catch{throw new HttpError(401,'Session rejected');}}
export function sessionToken(request:Request):string|undefined{const value=cookie(request,'__Host-custodia');if(!value)return;const session=open(value);if(typeof session.accessToken!=='string'||session.expiresAt<Date.now())throw new HttpError(401,'Session expired');return session.accessToken;}
export function startLogin(){const state=randomBytes(32).toString('base64url');const nonce=randomBytes(32).toString('base64url');const verifier=randomBytes(48).toString('base64url');const url=httpsUrl('OIDC_AUTHORIZATION_URL');const params={client_id:required('OIDC_CLIENT_ID'),redirect_uri:required('PUBLIC_ORIGIN')+'/api/auth/callback',response_type:'code',scope:required('OIDC_LOGIN_SCOPES'),state,nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'};for(const[k,v]of Object.entries(params))url.searchParams.set(k,v);return {url,value:seal({state,nonce,verifier,expiresAt:Date.now()+300000})};}
export async function finishLogin(request:Request){const saved=cookie(request,'__Host-custodia-login');if(!saved)throw new HttpError(401,'Login expired');const flow=open(saved);const url=new URL(request.url);if(flow.expiresAt<Date.now()||url.searchParams.get('state')!==flow.state||!url.searchParams.get('code'))throw new HttpError(401,'Login rejected');const response=await fetch(httpsUrl('OIDC_TOKEN_URL'),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:required('OIDC_CLIENT_ID'),client_secret:required('OIDC_CLIENT_SECRET'),redirect_uri:required('PUBLIC_ORIGIN')+'/api/auth/callback',code:url.searchParams.get('code')!,code_verifier:flow.verifier}),signal:AbortSignal.timeout(5000),redirect:'error',cache:'no-store'});if(!response.ok)throw new HttpError(401,'Token exchange failed');const token=await response.json();const jwks=createRemoteJWKSet(httpsUrl('OIDC_JWKS_URL'));const {payload}=await jwtVerify(token.id_token,jwks,{issuer:required('OIDC_ISSUER'),audience:required('OIDC_CLIENT_ID'),algorithms:['RS256','ES256'],requiredClaims:['exp','sub','nonce']});if(payload.nonce!==flow.nonce||typeof token.access_token!=='string'||token.access_token.length>2400)throw new HttpError(401,'Identity rejected');const access=await jwtVerify(token.access_token,jwks,{issuer:required('OIDC_ISSUER'),audience:required('OIDC_AUDIENCE'),algorithms:['RS256','ES256'],requiredClaims:['exp','sub','tenant_id']});return {value:seal({accessToken:token.access_token,expiresAt:Math.min(access.payload.exp!*1000,Date.now()+3600000)}),maxAge:Math.max(1,Math.min(3600,access.payload.exp!-Math.floor(Date.now()/1000)))};}
