import ExcelJS from 'exceljs';
import {createHash} from 'node:crypto';
import {csvCell,utf8} from './sanitize';
export function flatten(value:unknown,path='$',rows:{path:string,value:unknown}[]=[]){if(rows.length>10000)throw Error('Export row limit exceeded');if(value!==null&&typeof value==='object'){for(const[k,v]of Object.entries(value))flatten(v,path+'/'+k.replaceAll('~','~0').replaceAll('/','~1'),rows);}else rows.push({path,value});return rows;}
export async function compileExport(document:{id:string,mime:string,bytes:Buffer},format:'csv'|'xlsx'|'jsonld'|'pdf'){
 if(format==='pdf'){if(document.mime!=='application/pdf')throw Error('PDF export requires PDF source');return {bytes:document.bytes,mime:'application/pdf',extension:'pdf',hash:createHash('sha256').update(document.bytes).digest('hex')};}
 if(document.mime==='application/pdf')throw Error('Flattened PDF cannot be converted to structured data without verified OCR');const source=document.mime==='application/json'?JSON.parse(utf8(document.bytes)):utf8(document.bytes);const rows=flatten(source);let bytes:Buffer;let mime:string;
 if(format==='csv'){bytes=Buffer.from('"path","value"\r\n'+rows.map(r=>csvCell(r.path)+','+csvCell(r.value)).join('\r\n')+'\r\n','utf8');mime='text/csv; charset=utf-8';}else if(format==='jsonld'){bytes=Buffer.from(JSON.stringify({'@context':{documentId:'https://schema.org/identifier',entries:'https://schema.org/hasPart',path:'https://schema.org/name',value:'https://schema.org/value'},documentId:document.id,entries:rows}),'utf8');mime='application/ld+json; charset=utf-8';}else{const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet('Redacted records');sheet.columns=[{header:'Path',key:'path',width:50},{header:'Value',key:'value',width:80}];for(const row of rows){const value=typeof row.value==='object'?JSON.stringify(row.value):String(row.value??'');if(value.length>32767)throw Error('Cell exceeds Excel limit');sheet.addRow({path:row.path,value});}sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter='A1:B1';bytes=Buffer.from(await workbook.xlsx.writeBuffer());mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';}
 if(bytes.length>20*1024*1024)throw Error('Export size limit exceeded');return {bytes,mime,extension:format==='jsonld'?'jsonld':format,hash:createHash('sha256').update(bytes).digest('hex')};
}
