import {containment} from '../backend/containment';
import {createHash,randomUUID} from 'node:crypto';
import type {Principal} from '../backend/auth';
import {transaction,canonical,signature} from '../backend/database';
import {HttpError,required} from '../backend/config';
import {encrypt,decrypt} from './crypto';
import {Policy,redactText,redactStructured,utf8,type RedactionPolicy} from './sanitize';
import {sanitizePdf} from './pdf';
const digest=(data:Buffer)=>createHash('sha256').update(data).digest('hex');
export async function ingest(p:Principal,requestId:string,name:string,mime:string,bytes:Buffer,policyInput:unknown){await containment();const policy=Policy.parse(policyInput);if(bytes.length===0||bytes.length>5*1024*1024)throw new HttpError(413,'Document size rejected');const id=randomUUID();let sanitized:Buffer;let report:unknown;
 if(mime==='application/pdf'){const result=await sanitizePdf(bytes,policy);sanitized=result.bytes;report=result.report;}else if(mime==='text/plain'){const result=redactText(utf8(bytes),policy);sanitized=Buffer.from(result.text,'utf8');report={matches:result.count,method:'text'};}else if(mime==='application/json'){const result=redactStructured(JSON.parse(utf8(bytes)),policy);sanitized=Buffer.from(JSON.stringify(result.value),'utf8');report={matches:result.count,method:'structural'};}else throw new HttpError(415,'Only UTF-8 text, JSON and searchable text PDF inputs are supported');
 const keyId=required('DOCUMENT_KEY_ID');const sourceHash=digest(bytes);const sanitizedHash=digest(sanitized);const safeName=redactText(name,policy).text.slice(0,200);
 return transaction(p,async c=>{await c.query('INSERT INTO custodia.documents(tenant_id,id,request_id,name,mime,key_id,source_cipher,sanitized_cipher,source_sha256,sanitized_sha256,policy_cipher,report) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[p.tenant,id,requestId,safeName,mime,keyId,encrypt(bytes,p.tenant,id,'source',keyId),encrypt(sanitized,p.tenant,id,'sanitized',keyId),sourceHash,sanitizedHash,encrypt(Buffer.from(JSON.stringify(policy)),p.tenant,id,'policy',keyId),JSON.stringify(report)]);const audit=canonical({tenant:p.tenant,id,actor:p.actor,type:'ingested',sourceHash,sanitizedHash,policyVersion:policy.version});await c.query('INSERT INTO custodia.document_events(tenant_id,id,document_id,actor,event_type,hash,signed_payload,key_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[p.tenant,randomUUID(),id,p.actor,'ingested',signature(audit),audit,required('LEDGER_KEY_ID')]);return {id,name:safeName,mime,status:'review',version:'1',report,sanitizedHash};});}
export async function approve(p:Principal,id:string,version:string){return transaction(p,async c=>{const row=await c.query("UPDATE custodia.documents SET status='approved',approved_by=$1,approved_at=now(),version=version+1 WHERE id=$2 AND version=$3 AND status='review' RETURNING id,version::text,sanitized_sha256",[p.actor,id,version]);if(!row.rowCount)throw new HttpError(409,'Document missing, approved or version changed');const audit=canonical({tenant:p.tenant,id,actor:p.actor,type:'approved',version,hash:row.rows[0].sanitized_sha256});await c.query('INSERT INTO custodia.document_events(tenant_id,id,document_id,actor,event_type,hash,signed_payload,key_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[p.tenant,randomUUID(),id,p.actor,'approved',signature(audit),audit,required('LEDGER_KEY_ID')]);return row.rows[0];});}
export async function reviewed(p:Principal,id:string,approved:boolean){return transaction(p,async c=>{const result=await c.query('SELECT id,name,mime,key_id,sanitized_cipher,sanitized_sha256,status,version::text,report,policy_cipher FROM custodia.documents WHERE id=$1',[id]);const row=result.rows[0];if(!row)throw new HttpError(404,'Document not found');if(approved&&row.status!=='approved')throw new HttpError(409,'Named reviewer approval required');const bytes=decrypt(row.sanitized_cipher,p.tenant,id,'sanitized',row.key_id);if(digest(bytes)!==row.sanitized_sha256)throw Error('Document integrity failure');const policy:RedactionPolicy=Policy.parse(JSON.parse(decrypt(row.policy_cipher,p.tenant,id,'policy',row.key_id).toString('utf8')));return {id,name:row.name as string,mime:row.mime as string,bytes,policy,status:row.status,version:row.version,report:row.report};});}
export async function exportAudit(p:Principal,id:string,format:string,hash:string){return transaction(p,async c=>{const row=await c.query("SELECT 1 FROM custodia.documents WHERE id=$1 AND status='approved' FOR SHARE",[id]);if(!row.rowCount)throw new HttpError(409,'Approved document required');const proof=canonical({tenant:p.tenant,documentId:id,actor:p.actor,type:'exported',format,hash,keyId:required('LEDGER_KEY_ID')});const signed=signature(proof);await c.query('INSERT INTO custodia.document_events(tenant_id,id,document_id,actor,event_type,hash,signed_payload,key_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[p.tenant,randomUUID(),id,p.actor,'exported',signed,proof,required('LEDGER_KEY_ID')]);return {proof,signature:signed,keyId:required('LEDGER_KEY_ID')};});}
