import {lookup} from 'node:dns/promises';
import {request} from 'node:https';
import {required,HttpError} from '../backend/config';
import {transaction} from '../backend/database';
import type {Principal} from '../backend/auth';
import {configuration} from './adapters';
import {unseal} from './store';
import {requestJson} from './transport';
import {ingest} from '../documents/store';
import {z} from 'zod';
export function publicIPv4(value:string){const n=value.split('.').map(Number);return n.length===4&&n.every(v=>Number.isInteger(v)&&v>=0&&v<=255)&&n[0]!==0&&n[0]!==10&&n[0]!==127&&n[0]<224&&!(n[0]===169&&n[1]===254)&&!(n[0]===172&&n[1]>=16&&n[1]<=31)&&!(n[0]===192&&n[1]===168)&&!(n[0]===100&&n[1]>=64&&n[1]<=127)&&!(n[0]===198&&(n[1]===18||n[1]===19));}
export async function download(url:URL){const allowed=required('GRAPH_DOWNLOAD_HOSTS').split(',').map(s=>s.trim().toLowerCase());if(url.protocol!=='https:'||url.port||url.username||url.password||!allowed.includes(url.hostname))throw new HttpError(400,'Download host not approved');const addresses=await lookup(url.hostname,{all:true,family:4});if(!addresses.length||addresses.some(a=>!publicIPv4(a.address)))throw new HttpError(400,'Download network boundary rejected');const address=addresses[0].address;
 return new Promise<Buffer>((resolve,reject)=>{const chunks:Buffer[]=[];let size=0;const req=request(url,{method:'GET',rejectUnauthorized:true,minVersion:'TLSv1.2',lookup:(_hostname,_options,callback)=>callback(null,address,4)},res=>{if(res.statusCode!==200){res.resume();reject(new HttpError(502,'Provider binary download failed'));return;}res.on('data',(chunk:Buffer)=>{size+=chunk.length;if(size>5*1024*1024){req.destroy(new HttpError(413,'Provider document exceeds limit'));return;}chunks.push(chunk);});res.on('end',()=>resolve(Buffer.concat(chunks)));res.on('error',()=>reject(new HttpError(502,'Binary stream failed')));});const timeout=setTimeout(()=>req.destroy(new HttpError(504,'Binary download deadline exceeded')),15000);req.on('close',()=>clearTimeout(timeout));req.on('error',()=>reject(new HttpError(502,'Provider download transport failed')));req.end();});}
export async function importGraph(p:Principal,connectorId:string,itemId:string,requestId:string,policy:unknown){const config=await transaction(p,async c=>{const connector=(await c.query('SELECT config FROM custodia.connectors WHERE id=$1',[connectorId])).rows[0];if(!connector)throw new HttpError(404,'Connector not found');const item=(await c.query('SELECT 1 FROM custodia.connector_items WHERE connector_id=$1 AND external_id=$2 AND NOT deleted',[connectorId,itemId])).rows[0];if(!item)throw new HttpError(404,'Indexed source item not found');return configuration.parse(unseal(connector.config,`${p.tenant}:${connectorId}:config`));});if(config.provider!=='graph')throw new HttpError(415,'Binary import currently supports Graph drives');
 const token=z.object({access_token:z.string()}).parse(await requestJson(new URL(`https://login.microsoftonline.com/${config.directoryId}/oauth2/v2.0/token`),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'client_credentials',client_id:config.clientId,client_secret:config.clientSecret,scope:'https://graph.microsoft.com/.default'}).toString()}));const metadata=z.object({id:z.string(),name:z.string().max(200),file:z.object({mimeType:z.string()}),'@microsoft.graph.downloadUrl':z.url()}).parse(await requestJson(new URL(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(config.driveId)}/items/${encodeURIComponent(itemId)}`),{headers:{Authorization:`Bearer ${token.access_token}`}}));if(metadata.id!==itemId)throw Error('Provider item identity mismatch');const bytes=await download(new URL(metadata['@microsoft.graph.downloadUrl']));try{return await ingest(p,requestId,metadata.name,metadata.file.mimeType,bytes,policy);}finally{bytes.fill(0);}}
