'use client';
import { useState } from 'react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
const money = (n:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export function ROI(){
 const [step,setStep]=useState(1); const [v,setV]=useState({headcount:12,salary:140000,cloud:8000,audits:2,auditCost:15000,latency:48,target:24,reclaim:10,compute:15,auditReduction:20,annual:24500,implementation:8000});
 const fields = step===1 ? [['headcount','Engineering / operations headcount',0,10000],['salary','Loaded annual cost per person ($)',0,1000000],['cloud','Monthly cloud compute spend ($)',0,10000000],['audits','Security audits per year',0,52],['auditCost','Internal cost per audit ($)',0,1000000],['latency','Current processing time (hours)',1,8760]] : [['target','Target processing time (hours)',1,8760],['reclaim','Capacity reclaimed (%)',0,100],['compute','Compute reduction (%)',0,100],['auditReduction','Audit effort reduction (%)',0,100],['annual','Annual subscription ($)',0,10000000],['implementation','One-time implementation ($)',0,10000000]];
 const labor=v.headcount*v.salary*v.reclaim/100, cloud=v.cloud*12*v.compute/100,audit=v.audits*v.auditCost*v.auditReduction/100,gross=labor+cloud+audit,net=gross-v.annual,three=net*3-v.implementation;
 const chart=[1,2,3].map(year=>({year:`Year ${year}`,net:Math.round(net*year-v.implementation)}));
 return <div className="grid gap-8 lg:grid-cols-2"><div className="rounded-xl border border-rule bg-surface p-6"><div className="mb-6 flex gap-3">{[1,2].map(s=><button key={s} onClick={()=>setStep(s)} aria-pressed={step===s} className={`min-h-11 rounded px-4 text-sm ${step===s?'bg-paper text-ink':'border border-rule text-muted'}`}>{s===1?'1. Baseline':'2. Assumptions'}</button>)}</div><div className="grid gap-5 sm:grid-cols-2">{fields.map(([key,label,min,max])=><label className="text-xs text-muted" key={key}><span className="mb-2 block">{label}</span><input className="field text-base text-paper" type="number" min={min} max={max} value={v[key as keyof typeof v]} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))setV({...v,[key]:Math.min(Number(max),Math.max(Number(min),n))});}} /></label>)}</div><p className="caption mt-6">Planning model, not a measured product result. Reclaimed labor is capacity value, not guaranteed cash savings. Edit every assumption to match your organization.</p></div><div><div className="grid grid-cols-2 gap-6 border-b border-rule pb-6"><div><p className="eyebrow">Three-year net value</p><p className="mt-2 font-display text-4xl">{money(three)}</p></div><div><p className="eyebrow">Break-even</p><p className="mt-2 font-display text-4xl">{net>0?`${Math.ceil(v.implementation/(net/12))} months`:'Not reached'}</p></div></div><div className="mt-6 h-52" aria-label="Projected cumulative net value by year"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid stroke="var(--color-rule)" vertical={false}/><XAxis dataKey="year" stroke="var(--color-muted)"/><YAxis stroke="var(--color-muted)" width={70} tickFormatter={n=>`${Math.round(n/1000)}k`}/><Tooltip formatter={n=>money(Number(n))} contentStyle={{background:'var(--color-surface)',border:'1px solid var(--color-rule)',color:'var(--color-paper)'}}/><Bar dataKey="net" name="Cumulative net value" fill="var(--color-sage)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><dl className="mt-4 space-y-2 text-sm">{[['Annual capacity value',labor],['Annual compute savings',cloud],['Annual audit effort value',audit],['Annual subscription',-v.annual]].map(([k,n])=><div key={k} className="flex justify-between gap-3"><dt className="text-muted">{k}</dt><dd>{money(Number(n))}</dd></div>)}</dl><p className="caption mt-4">Processing multiplier: {(v.latency/v.target).toFixed(2)}× under your target assumption. Formula: annual capacity + compute + audit value − subscription; subtract implementation once. No discounting, tax, or growth assumed.</p></div></div>
}
